server:
  port: 8084

spring:
  application:
    name: alert-service

  kafka:
    bootstrap-servers: localhost:9094
#    producer:
#      default-topic: alert-service
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: alert-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: alertingEvent:com.bharath.kafka.event.AlertingEvent

  datasource:
    url: jdbc:mysql://localhost:3306/home_energy_tracker
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

device:
  service:
    url: http://localhost:8081/api/v1/device

user:
  service:
    url: http://localhost:8080/api/v1/user